"""Build app/web/static/ds/_ds_bundle.js — the precompiled design-system namespace.

Replicates ds-loader.js's runtime module→namespace transform at build time, so
the browser skips 22 synchronous XHRs + evaluations. Components are plain
React.createElement (no JSX), so this needs nothing beyond the stdlib.
"""

import re
from pathlib import Path

DS = Path(__file__).resolve().parents[1] / "app" / "web" / "static" / "ds"

FILES = [
    "components/icons/Icon.jsx",
    "components/actions/Button.jsx",
    "components/actions/IconButton.jsx",
    "components/indicators/Badge.jsx",
    "components/indicators/StatusPill.jsx",
    "components/indicators/Sparkline.jsx",
    "components/indicators/StatCard.jsx",
    "components/forms/Input.jsx",
    "components/forms/Select.jsx",
    "components/forms/SearchInput.jsx",
    "components/forms/Switch.jsx",
    "components/forms/Checkbox.jsx",
    "components/navigation/Tabs.jsx",
    "components/navigation/Stepper.jsx",
    "components/navigation/Pagination.jsx",
    "components/shell/SidebarNav.jsx",
    "components/shell/TopBar.jsx",
    "components/data/Alert.jsx",
    "components/data/DataTable.jsx",
    "components/data/KeyValue.jsx",
    "components/data/CodeBlock.jsx",
    "components/data/ActionChoiceCard.jsx",
]


def transform(source: str) -> tuple[str, str, str]:
    imports: list[str] = []

    def collect_imports(match: re.Match[str]) -> str:
        for name in match.group(1).split(","):
            name = name.strip()
            if name:
                imports.append(name)
        return ""

    source = re.sub(r"import\s*\{([^}]*)\}\s*from\s*'[^']*';?", collect_imports, source)
    source = re.sub(r"import\s+React\s+from\s+'react';?", "", source)

    exports: list[tuple[str, str]] = []

    def collect_export_fn(match: re.Match[str]) -> str:
        exports.append((match.group(1), match.group(1)))
        return "function " + match.group(1)

    source = re.sub(r"export\s+function\s+([A-Za-z0-9_]+)", collect_export_fn, source)

    def collect_export_block(match: re.Match[str]) -> str:
        for part in match.group(1).split(","):
            pieces = re.split(r"\s+as\s+", part.strip())
            if pieces[0]:
                exports.append((pieces[0], pieces[1] if len(pieces) > 1 else pieces[0]))
        return ""

    source = re.sub(r"export\s*\{([^}]*)\};?", collect_export_block, source)

    pre = (
        "var " + ", ".join(f"{name} = NS.{name}" for name in imports) + ";" if imports else ""
    )
    post = " ".join(f"NS.{alias} = {name};" for name, alias in exports)
    return pre, source, post


def main() -> None:
    parts = [
        "// Generated by scripts/build_ds_bundle.py — do not edit.",
        "(function () {",
        "  var NS = {};",
        "  var React = window.React;",
    ]
    for relative in FILES:
        pre, source, post = transform((DS / relative).read_text())
        parts.append(f"  // ── {relative}")
        parts.append("  (function (NS, React) {")
        parts.append(pre)
        parts.append(source)
        parts.append(post)
        parts.append("  })(NS, React);")
    parts.append("  window.__DS_BUNDLE = NS;")
    parts.append("})();")
    out = DS / "_ds_bundle.js"
    out.write_text("\n".join(parts))
    print(f"wrote {out} ({out.stat().st_size} bytes, {len(FILES)} components)")


if __name__ == "__main__":
    main()
